### ISSUE TITLE
クリスマス

### ISSUE THREAD

**Issue by Atria64** [materialofmouse/door#1]
クリスマスが近づいているので、クリスマスっぽい飾りをつけたいです。

**Comment by materialofmouse** [comment]
認可

**Comment by materialofmouse** [comment]
@Atria64 ブランチを切って、どういった物がいいかを書き出しておいてください。
ファイルのタイトル、拡張子はchristmas.mdでよろしくおねがいします。
書き方は任せます。

**Comment by Atria64** [comment]
わかりました。
アサインお願いします。
@Oxypetalum7 アイディアこのツリーにお願いします。

**Comment by Atria64** [comment]
拡張子は`christmas.md`とのことですが、年度をわかりやすくするために`2020_christmas.md`にするのはどうでしょうか

**Comment by Oxypetalum7** [comment]
取り敢えずクリスマスリースは鉄板だと思います。

**Comment by materialofmouse** [comment]
@Atria64 2020_christmasにするよりか2020というディレクトリを作成し、その中にchristmas.mdを入れるのがいいのかなと思います。他のイベントも一年にいっかいしかないので、年度ごとにディレクトリを分けて、イベント名.mdにするのがいいと思います。

**Comment by materialofmouse** [comment]
@Atria64 @Oxypetalum7 
この度はクリスマスの飾り付けに協力していただきありがとうございました。
提示されたリストの中からできるだけ希望に沿う形で購入、取り付けの方を行いました。もしお時間に余裕がありましたら一度立ち寄ってみることをおすすめします。
