### ISSUE TITLE
ドアの範囲がわからない

### ISSUE THREAD

**Issue by yamauch** [materialofmouse/door#7]
ハロウィンの時のドア装飾はドアに張り付けるタイプの装飾のみでしたが、数日前のクリスマスの装飾ではドア直下にサンタクロースを模したミラーボールを設置していました。  
正月のドア装飾を前に一度装飾する範囲を確認したいです。 
ドア直下の装飾が認められる場合門松などを設置したいと思っています。

**Comment by materialofmouse** [comment]
とても大事な質問ありがとうございます。
とりあえず、僕の意向として問題のないものは
### 問題のないもの
- 玄関のドア
- 玄関の前
- 玄関の中
- 玄関の中の棚上
は可能としています。
基本的には家の住人以外の人が最も見る場所。であれば問題ないかなと思います。
しかし、厳密にここまではOKという線引ができるものではないと考えているので、なにか飾りつけを行う際に都度確認を取るといいと思います。
これで大丈夫そうでしたらクローズお願いします。

**Comment by yamauch** [comment]
回答ありがとうございます。
隣人問題に発展すると危ないのでそちらのリストを参考にして設置するものを検討したいと思います。
